options hid_apple fnmode=2
options hid_apple swap_fn_leftctrl=1
options hid_apple swap_opt_cmd=1
options hid_appletb_kbd mode=1
options hid_appletb_kbd fntoggle=1
options hid_appletb_kbd dim_timeout=5
options hid_appletb_kbd idle_timeout=2
