MODULES_LIST=(
    # PREBUILD
    "prebuild/device_structure.sh"
    "prebuild/safety_check.sh"
    "prebuild/partitions.sh"
    "prebuild/luks.sh"
    "prebuild/format.sh"
    "prebuild/mount.sh"
    "prebuild/debootstrap.sh|amd64 trixie"
    "prebuild/sources.sh|trixie"
    "prebuild/fstab.sh"
    "prebuild/crypttab.sh"
    "base/locales_generation.sh|en_GB|pl_PL"
    "base/locales_update.sh|en_GB:en:C:pl|LANG=en_GB|LC_MEASUREMENT=pl_PL|LC_MONETARY=pl_PL|LC_NUMERIC=pl_PL|LC_PAPER=pl_PL|LC_TELEPHONE=pl_PL|LC_TIME=pl_PL"
    "base/hosts.sh|ptrF15W"
    "base/utils.sh"
    "base/timezone.sh|Europe/Warsaw"
    "base/keyboard_console.sh|fusion"
    "base/admin.sh|Admin"
    "extra/save_random_luks_password.sh"
    "base/initram.sh"
    "extra/install_deb.sh|yubikey/fido2luks_0.0.3-1_all.deb"
    "base/kernel.sh|amd64"

    # NETWORK
    "base/network_manager.sh"

    # FUSION DRIVERS & FIRMWARE
    "extra/install_full.sh|intel-microcode" # stability & security
    "extra/install_full.sh|firmware-misc-nonfree" # many helpful stuff
    "extra/install_full.sh|intel-media-va-driver-non-free" # video codecs
    "extra/install_full.sh|firmware-iwlwifi" # WiFi
    "extra/install_full.sh|firmware-realtek" # ethernet
    "extra/add_repo.sh|repos/tuxedo.sources" # Tuxedo Fusion 15 repo
    "extra/copy_user_config.sh|fusion/nvidia_post.sh|Desktop/___nvidia_post.sh|664"

    # FIREWALL
    "core/firewall.sh"

    # BATTERY
    "core/battery.sh"

    # AUDIO
    "core/audio.sh"

    # PLASMA
    "core/plasma.sh"

    # PACKAGE MANAGERS
    "core/discover_flathub.sh"

    # SESSION
    "extra/copy_system_config.sh|session/autologin.conf|etc/sddm.conf.d/autologin.conf|644"
    "extra/swap_in_file.sh|etc/sddm.conf.d/autologin.conf|USER|\$ADMIN_NAME"
    "extra/copy_user_config.sh|session/ksplashrc|.config/ksplashrc|600"
    "extra/copy_user_config.sh|session/ksmserverrc|.config/ksmserverrc|600"

    # FONTS
    "extra/install_full.sh|fonts-noto-core fonts-noto-cjk fonts-noto-cjk-extra fonts-noto-color-emoji"

    # VSCODIUM
    "extra/add_repo.sh|repos/vscodium.sources"
    "extra/install_full.sh|codium"

    # BOOTLOADER
    "base/grub.sh|grub-efi-amd64-signed shim-signed|--target=x86_64-efi --uefi-secure-boot --bootloader-id='Debian'|quiet splash"
)
