MODULES_LIST=(
    # PREBUILD
    "prebuild/stty_size.sh|tty0|100|320"
    "prebuild/device_structure.sh"
    "prebuild/safety_check.sh"
    "prebuild/partitions.sh"
    "prebuild/luks.sh"
    "prebuild/format.sh"
    "prebuild/mount.sh"
    "prebuild/debootstrap.sh|amd64 trixie"
    "prebuild/sources.sh|trixie"
    "prebuild/fstab.sh"
    "prebuild/crypttab.sh"
    "base/locales_generation.sh|en_GB|pl_PL"
    "base/locales_update.sh|en_GB:en:C:pl|LANG=en_GB|LC_MEASUREMENT=pl_PL|LC_MONETARY=pl_PL|LC_NUMERIC=pl_PL|LC_PAPER=pl_PL|LC_TELEPHONE=pl_PL|LC_TIME=pl_PL"
    "base/hosts.sh|ptrMB13W"
    "base/utils.sh"
    "base/timezone.sh|Europe/Warsaw"
    "base/keyboard_console.sh|mac-iso"
    "base/admin.sh|Admin"
    "extra/save_random_luks_password.sh"
    "base/initram.sh"
    "extra/install_deb.sh|yubikey/fido2luks.deb"
    "mac/t2.sh|trixie" #|7.0.12-1"
    "mac/early_boot_keyboard.sh"

    # NETWORK
    "base/network_manager.sh"
    "extra/copy_system_config.sh|apple_firmware/network-t2-ncm.rules|etc/udev/rules.d/99-network-t2-ncm.rules|644"
    "extra/copy_system_config.sh|apple_firmware/network-t2-ncm.conf|etc/NetworkManager/conf.d/99-network-t2-ncm.conf|644"
    "extra/copy_system_config.sh|apple_firmware/network-disable-mac-randomization.conf|etc/NetworkManager/conf.d/99-disable-mac-randomization.conf|644"

    # TOUCHBAR
    "extra/copy_system_config.sh|apple_firmware/touchbar-blacklist.conf|etc/modprobe.d/touchbar-blacklist.conf|644"
    "extra/copy_system_config.sh|apple_firmware/touchbar-options.conf|etc/modprobe.d/touchbar-options.conf|644"
    "extra/copy_service.sh|apple_firmware/touchbar-startup.service"
    "extra/copy_service.sh|apple_firmware/touchbar-shutdown.service"

    # ZRAM
    "extra/install_full.sh|systemd-zram-generator"
    "extra/copy_system_config.sh|zram/zram_full.conf|etc/systemd/zram-generator.conf|644"

    # ICON & LABEL
    "extra/copy_system_config.sh|icon_label/debian.icns|efi/.VolumeIcon.icns|755"
    "extra/copy_system_config.sh|icon_label/debian_label|efi/EFI/BOOT/.disk_label|755"
    "extra/copy_system_config.sh|icon_label/debian_label_2x|efi/EFI/BOOT/.disk_label_2x|755"

    # MAC & T2 FIRMWARE
    "extra/install_deb.sh|apple_firmware/macfw.deb"
    "extra/copy_service.sh|apple_firmware/bcm4377-suspend-fix.service"
    "extra/copy_system_config.sh|apple_firmware/wifi_reset|usr/local/bin/wifi_reset|755"
    "mac/drivers_firmware_mac.sh"

    # FIREWALL
    "core/firewall.sh"

    # FAN
    "mac/t2fanrd_hack.sh"
    "extra/copy_system_config.sh|apple_firmware/t2fand.conf|etc/t2fand.conf|644"

    # BATTERY
    "core/battery.sh"
    "extra/copy_system_config.sh|apple_firmware/battery_limit|usr/local/bin/battery_limit|755"

    # AUDIO
    "core/audio.sh"
    "extra/install_full.sh|apple-t2-audio-config"
    "extra/install_full.sh|t2-apple-audio-dsp-mic"

    # PLASMA
    "core/plasma.sh"

    # PACKAGE MANAGERS
    "core/discover_flathub.sh"

    # SESSION
    "extra/copy_system_config.sh|session/autologin.conf|etc/sddm.conf.d/autologin.conf|644"
    "extra/swap_in_file.sh|etc/sddm.conf.d/autologin.conf|USER|\$ADMIN_NAME"
    "extra/copy_user_config.sh|session/ksplashrc|.config/ksplashrc|600"
    "extra/copy_user_config.sh|session/ksmserverrc|.config/ksmserverrc|600"

    # FONTS
    "extra/install_full.sh|fonts-noto-core fonts-noto-cjk fonts-noto-cjk-extra fonts-noto-color-emoji"

    # VSCODIUM
    "extra/add_repo.sh|repos/vscodium.sources"
    "extra/install_full.sh|codium"

    # BOOTLOADER
    "base/grub.sh|grub-efi-amd64|--target=x86_64-efi --no-nvram --removable|quiet splash intel_iommu=on iommu=pt pm_async=off pcie_ports=native"
)
